apiVersion: apps/v1
kind: Deployment
metadata:
  name: company
spec:
  selector:
    matchLabels:
      app: company
  template:
    metadata:
      labels:
        app: company
    spec:
      containers:
      - name: company
        image: company
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 9091
